(define (thread-start/timeout! timeout thread)
  (let ((thread (thread-start! thread)))
    (let* ((flag (random-real))
           (join (thread-join! thread timeout flag)))
      (if (= join flag)
          (thread-terminate! thread)
          join))))

(define (eval-file file)
  (with-input-from-file file
    (lambda ()
      (let iter ((value (read)))
        (if (not (eof-object? value))
            (begin (print (eval value))
                   (iter (read))))))))
